basePath: /v1
definitions:
  v1.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
  v1.registerUserRequest:
    properties:
      deliveryAddress:
        example: Pushkina street
        type: string
      email:
        example: vadiminmail@gmail.com
        type: string
      lastName:
        example: Valov
        type: string
      name:
        example: Vadim
        type: string
      password:
        example: qwerty123
        type: string
    required:
    - deliveryAddress
    - email
    - lastName
    - name
    - password
    type: object
  v1.registerUserResponse:
    properties:
      deliveryAddress:
        example: Pushkina street
        type: string
      email:
        example: vadiminmail@gmail.com
        type: string
      id:
        example: d9e48656-ae36-4fde-af78-5f6250e11ead
        type: string
      lastName:
        example: Valov
        type: string
      name:
        example: Vadim
        type: string
    required:
    - deliveryAddress
    - email
    - id
    - lastName
    - name
    type: object
host: localhost:8080
info:
  contact: {}
  description: Delivery service
  title: Delivery service API
  version: "1.0"
paths:
  /user/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      operationId: register
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.registerUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.registerUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      summary: Register
      tags:
      - users
swagger: "2.0"
